# Generated by Django 5.2.4 on 2025-07-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
