# Generated by Django 5.2.4 on 2025-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_courseunit_uploadedfile_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='tag',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('personal_note', 'Personal Note'), ('study_material', 'Study Material'), ('question_bank', 'Question Bank')], default='study_material', max_length=20),
        ),
    ]
